apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repositories
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repositories
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-platform-config.git
    targetRevision: main
    path: platform/argocd/repositories
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
