apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-platform-config.git
    targetRevision: main
    path: platform/observability/grafana
    helm:
      releaseName: grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
