apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-platform-config.git
    targetRevision: main
    path: platform/collectors/alloy
    helm:
      releaseName: alloy
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-collectors
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio.io/rev: stable
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
