apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: gateway-api-config
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-platform-config.git
    targetRevision: main
    path: platform/gateway-api-config
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
