apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-managementgateway
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio-managementgateway
    app.kubernetes.io/part-of: k8s-playground
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-platform-config.git
    targetRevision: main
    path: platform/istio/managementgateway
    helm:
      releaseName: istio-managementgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
