apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-playground-kind-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: k8s-playground-kind-root
    app.kubernetes.io/part-of: k8s-playground
spec:
  project: default
  source:
    repoURL: https://github.com/mblayman/k8s-playground-argocd-apps.git
    targetRevision: HEAD
    path: clusters/kind/apps
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
